secrets: handle string types more careful
This fixes commit 0beb3f9c partial. With up to date cornice
and Py2 I get this error::

  .tox/py27/local/lib/python2.7/site-packages/cornice/service.py:493: in wrapper
      response = view_(request)
  tokenserver/views.py:268: in return_token
      node_secrets = secrets.get(user['node'])
  ../mozservices/mozsvc/secrets.py:95: in get
      node = six.u(node)

  TypeError: decoding Unicode is not supported

Signed-off-by: Markus Heiser <markus.heiser@darmarit.de>